sources:
  - name: raw
    meta:
        external_location: "models/raw/source_data/{name}"
    tables:
      - name: cv.json
        description: general information about me - contact info, education, work experience, and languages spoken
      - name: skills.csv
